/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Clinical Excellence Theme
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#44474d',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': '#75777e',
        'outline-variant': '#c5c6ce',
        'surface-tint': '#4e5f7e',
        'primary': '#031632',
        'on-primary': '#ffffff',
        'primary-container': '#1a2b48',
        'on-primary-container': '#8293b5',
        'inverse-primary': '#b6c7eb',
        'secondary': '#526069',
        'on-secondary': '#ffffff',
        'secondary-container': '#d3e2ed',
        'on-secondary-container': '#56656e',
        'tertiary': '#201500',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3a2800',
        'on-tertiary-container': '#b08d48',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#b6c7eb',
        'on-primary-fixed': '#081b38',
        'on-primary-fixed-variant': '#374765',
        'secondary-fixed': '#d6e5ef',
        'secondary-fixed-dim': '#bac9d3',
        'on-secondary-fixed': '#0f1d25',
        'on-secondary-fixed-variant': '#3b4951',
        'tertiary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#e9c176',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4201',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        // Accent colors
        'champagne': '#C5A059',
        'dental-blue': 'hsl(var(--dental-blue))',
        'dental-light-blue': 'hsl(var(--dental-light-blue))',
        'dental-green': 'hsl(var(--dental-green))',
        'dental-green-light': 'hsl(var(--dental-green-light))',
        'dental-gold': 'hsl(var(--dental-gold))',
        'dental-silver': 'hsl(var(--dental-silver))',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'container-max': '1200px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '64px',
      },
      fontFamily: {
        'display-lg': ['var(--font-source-serif-4)', 'serif'],
        'display-lg-mobile': ['var(--font-source-serif-4)', 'serif'],
        'headline-md': ['var(--font-source-serif-4)', 'serif'],
        'headline-sm': ['var(--font-source-serif-4)', 'serif'],
        'body-lg': ['var(--font-manrope)', 'sans-serif'],
        'body-md': ['var(--font-manrope)', 'sans-serif'],
        'label-bold': ['var(--font-manrope)', 'sans-serif'],
        'caption': ['var(--font-manrope)', 'sans-serif'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-left': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'stagger-container': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scroll-progress': {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'slide-up': 'slide-up 0.6s ease-out forwards',
        'slide-down': 'slide-down 0.6s ease-out forwards',
        'slide-left': 'slide-left 0.6s ease-out forwards',
        'slide-right': 'slide-right 0.6s ease-out forwards',
        'scale-in': 'scale-in 0.5s ease-out forwards',
        'stagger-container': 'stagger-container 0.6s ease-out forwards',
        'scroll-progress': 'scroll-progress 0.3s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulse-slow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}