/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // New Wellness & Spa Theme
        'surface': '#F9F8F6',
        'surface-dim': '#E8E5E1',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F4F2EE',
        'surface-container': '#EFECE7',
        'surface-container-high': '#EAE7E0',
        'surface-container-highest': '#E5E1D9',
        'on-surface': '#2B2D2C',
        'on-surface-variant': '#515553',
        'inverse-surface': '#2B2D2C',
        'inverse-on-surface': '#F9F8F6',
        'outline': '#838986',
        'outline-variant': '#D1D4D2',
        'surface-tint': '#4B7163',
        'primary': '#4B7163',
        'on-primary': '#FFFFFF',
        'primary-container': '#2A4038',
        'on-primary-container': '#CCE8DD',
        'inverse-primary': '#8CB3A3',
        'secondary': '#8A6D56',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#F2DCCB',
        'on-secondary-container': '#594435',
        'tertiary': '#606C76',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#D3E4F2',
        'on-tertiary-container': '#3C454D',
        'error': '#BA1A1A',
        'on-error': '#FFFFFF',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',
        'primary-fixed': '#CCE8DD',
        'primary-fixed-dim': '#8CB3A3',
        'on-primary-fixed': '#122B22',
        'on-primary-fixed-variant': '#325246',
        'secondary-fixed': '#F2DCCB',
        'secondary-fixed-dim': '#D6BFA9',
        'on-secondary-fixed': '#2B1B11',
        'on-secondary-fixed-variant': '#473223',
        'tertiary-fixed': '#D3E4F2',
        'tertiary-fixed-dim': '#A7C4D9',
        'on-tertiary-fixed': '#15242E',
        'on-tertiary-fixed-variant': '#2C3D49',
        'background': '#F9F8F6',
        'on-background': '#2B2D2C',
        'surface-variant': '#E5E1D9',
        // Accent colors
        'champagne': '#E0C89E',
        'sage': '#4B7163',
        'dental-blue': '#8CB3A3',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'container-max': '1200px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '64px',
      },
      fontFamily: {
        'display-lg': ['var(--font-playfair)', 'serif'],
        'display-lg-mobile': ['var(--font-playfair)', 'serif'],
        'headline-md': ['var(--font-playfair)', 'serif'],
        'headline-sm': ['var(--font-playfair)', 'serif'],
        'body-lg': ['var(--font-outfit)', 'sans-serif'],
        'body-md': ['var(--font-outfit)', 'sans-serif'],
        'label-bold': ['var(--font-outfit)', 'sans-serif'],
        'caption': ['var(--font-outfit)', 'sans-serif'],
      },
      fontSize: {
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'slide-left': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'stagger-container': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scroll-progress': {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'slide-up': 'slide-up 0.6s ease-out forwards',
        'slide-down': 'slide-down 0.6s ease-out forwards',
        'slide-left': 'slide-left 0.6s ease-out forwards',
        'slide-right': 'slide-right 0.6s ease-out forwards',
        'scale-in': 'scale-in 0.5s ease-out forwards',
        'stagger-container': 'stagger-container 0.6s ease-out forwards',
        'scroll-progress': 'scroll-progress 0.3s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulse-slow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}